# Generated by Django 4.1 on 2022-09-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_approval_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
