# Generated by Django 4.1 on 2022-09-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_approval_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='user',
        ),
        migrations.AddField(
            model_name='approval',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.userextend'),
        ),
    ]
