# Generated by Django 4.1 on 2022-09-06 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_approval_user_approval_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='approvals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.approval'),
        ),
        migrations.RemoveField(
            model_name='approval',
            name='user',
        ),
        migrations.AddField(
            model_name='approval',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.userextend'),
        ),
    ]
