# Generated by Django 4.1 on 2022-09-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_userextend_approvals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='approvals',
        ),
    ]
