# Generated by Django 4.1 on 2022-09-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_approvedpost_alter_userextend_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovedPost',
        ),
        migrations.AlterField(
            model_name='userextend',
            name='post',
            field=models.ManyToManyField(to='myapp.approval'),
        ),
    ]
