# Generated by Django 4.1 on 2022-09-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_delete_approvedpost_alter_userextend_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextend',
            old_name='post',
            new_name='approvals',
        ),
    ]
