# Generated by Django 4.1 on 2022-09-06 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_approvedpost_alter_userextend_approvals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='approvals',
        ),
        migrations.AddField(
            model_name='userextend',
            name='approvals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.approvedpost'),
        ),
    ]
