# Generated by Django 4.1 on 2022-09-06 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_remove_userextend_approvals_userextend_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.userextend'),
        ),
    ]
