# Generated by Django 4.1 on 2022-09-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_rename_post_volunteeringoption_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
    ]
