# Generated by Django 4.1 on 2022-09-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_rename_approvedpost_userapproval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Approval',
            new_name='ApprovalToConfirm',
        ),
    ]
