# Generated by Django 4.1.1 on 2022-09-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_rename_approval_approvaltoconfirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
