# Generated by Django 4.1 on 2022-09-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_stores_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='userextend',
            name='coupons_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextend',
            name='coupons_list',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='userextend',
            name='date_list',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
