# Generated by Django 4.1 on 2022-09-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_rename_stores_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApprovedPost',
            new_name='UserApproval',
        ),
    ]
