# Generated by Django 4.2.7 on 2023-11-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_rename_approval_approvaltoconfirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeringoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
