# Generated by Django 4.1 on 2022-09-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_feature_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
