# Generated by Django 4.1 on 2022-09-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_post_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='value',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
