# Generated by Django 4.1 on 2022-09-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_feature_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='coupons_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextend',
            name='coupons_list',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='userextend',
            name='date_list',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
