# Generated by Django 4.1 on 2022-09-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_feature_icon_userextend_coupons_counter_and_more'),
        ('myapp', '0021_alter_post_value'),
    ]

    operations = [
    ]
