# Generated by Django 4.1 on 2022-09-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_aproval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aproval',
            new_name='Approval',
        ),
    ]
