# Generated by Django 4.1 on 2022-09-05 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_approval_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.userextend'),
        ),
    ]
