# Generated by Django 4.1 on 2022-09-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_approval_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='date',
        ),
    ]
