# Generated by Django 4.1 on 2022-09-06 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_remove_approval_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
