# Generated by Django 4.1 on 2022-09-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_userextend_approvals_remove_approval_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='approvals',
        ),
    ]
