# Generated by Django 4.1 on 2022-09-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_post_user_delete_approvedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='userextend',
            name='post',
            field=models.ManyToManyField(to='myapp.post'),
        ),
    ]
