# Generated by Django 4.1 on 2022-09-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_remove_post_user_userextend_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='userextend',
            name='post',
            field=models.ManyToManyField(to='myapp.approvedpost'),
        ),
    ]
