# Generated by Django 4.1 on 2022-09-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_approvedpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedpost',
            name='is_approved',
            field=models.BooleanField(default=None),
        ),
    ]
